title: log(a)
description: escape from the box of “DESCRIPTION”
theme: just-the-docs

url: https://logaaaa.github.io

aux_links:
  aboutME: https://www.instagram.com/logaaaaaaaaaa

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "back to top"

footer_content: "Copyright &copy; log(a). Distributed by an <a href=\"https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0 license."
