title: log(a)
description: escape from the box of “DESCRIPTION”
theme: just-the-docs

url: https://logaaaa.github.io

aux_links:
  aboutME: https://www.instagram.com/logaaaaaaaaaa

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
