title: Loga Autonomous Archiving
description: escape from the box of “DESCRIPTION”
theme: just-the-docs

url: https://logaaaa.github.io

aux_links:
  Template Repository: https://www.instagram.com/logaaaaaaaaaa
